// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller.js"
application.register("chatroom-subscription", ChatroomSubscriptionController)


import LocationAutocompleteController from "./location_autocomplete_controller.js"
application.register("location-autocomplete", LocationAutocompleteController)

import MapController from "./map_controller.js"
application.register("map", MapController)

// import SearchUsersController from "./search_users_controller.js"
// application.register("search-users", SearchUsersController)
